# Generated by Django 6.0.7 on 2026-07-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reporttemplate_email_body_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='ai_prompt',
            field=models.TextField(blank=True, help_text='Custom instructions for the AI', null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='enable_ai_summary',
            field=models.BooleanField(default=False),
        ),
    ]
