# Generated by Django 6.0.7 on 2026-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_reporttemplate_ai_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
