# Generated by Django 6.0.7 on 2026-07-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_executionlog_is_deleted_from_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='is_resolved_failure',
            field=models.BooleanField(default=False),
        ),
    ]
