# Generated by Django 6.0.7 on 2026-07-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_executionlog_is_resolved_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
