# Generated by Django 6.0.7 on 2026-07-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_schedule_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='branding_color',
            field=models.CharField(default='#1e3c72', max_length=7),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='branding_logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding_logos/'),
        ),
    ]
