# Generated by Django 6.0.7 on 2026-07-21 09:01

import reports.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_reporttemplate_branding_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='auth_token',
            field=reports.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
