# Generated by Django 6.0.7 on 2026-07-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_datasource_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
