# Generated by Django 6.0.7 on 2026-07-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='endpoint',
            field=models.CharField(max_length=500),
        ),
    ]
