# Generated by Django 6.0.7 on 2026-07-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_datasource_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
