# Generated by Django 6.0.7 on 2026-07-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_executionlog_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='job_name_snapshot',
            field=models.CharField(blank=True, help_text='Preserves the job name if the job is deleted', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='reports.job'),
        ),
    ]
