# Generated by Django 6.0.7 on 2026-07-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_executionlog_job_name_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='chart_type',
            field=models.CharField(blank=True, choices=[('bar', 'Bar Chart'), ('pie', 'Pie Chart')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='has_chart',
            field=models.BooleanField(default=False),
        ),
    ]
