# Generated by Django 6.0.7 on 2026-07-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reporttemplate_chart_type_reporttemplate_has_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='email_body_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
