# Generated by Django 6.0.7 on 2026-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_executionlog_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='is_deleted_from_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='is_deleted_from_reports',
            field=models.BooleanField(default=False),
        ),
    ]
