# Generated by Django 6.0.7 on 2026-07-23 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_datasource_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='reports.job'),
        ),
    ]
