# Generated by Django 6.0.7 on 2026-07-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_alter_executionlog_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cron_expression',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_of_day',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
